version: 0.{build}
skip_tags: true
cache: C:\Users\appveyor\AppData\Local\NuGet\Cache
build_script:
- mkdir output
- echo "HI" > output\matt
- 7z a output%APPVEYOR_BUILD_VERSION%.zip output/*
test: off
artifacts:
- path: output*.zip
  name: diego-windows
deploy:
- provider: S3
  access_key_id: AKIAJ3M5ORCAISPRT22Q
  secret_access_key:
    secure: lMbaCusTBxZpIbSzoILyHMBkz+sVH7EwgAqI3sAVYAM92OcIzlzq1IzcB8MmnRvZ
  region: us-east-1
  bucket: diego-windows-release
  artifact: diego-windows
  set_public: true
  on:
    branch: appveyor-test
clone_folder: c:\diego-windows-release
branches:
  only:
  - master
  - /appveyor/
